---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[pm-postgresql::default]
    verifier:
      inspec_tests:
        - test/smoke/recipes/default
    attributes:

  - name: client
    run_list:
      - recipe[pm-postgresql::client]
    verifier:
      inspec_tests:
        - test/smoke/recipes/client
    attributes:

  - name: server
    run_list:
      - recipe[pm-postgresql::server]
    verifier:
      inspec_tests:
        - test/smoke/recipes/server
    attributes:
      postgresql:
        password:
          postgres: supersecret

  - name: create_database
    run_list:
      - recipe[pm-postgresql::server]
      - recipe[postgresql::ruby]
      - recipe[test::create_database]
    verifier:
      inspec_tests:
        - test/smoke/resources/create_database_test.rb
    attributes:
      postgresql:
        password:
          postgres: supersecret
  - name: drop_database
    run_list:
      - recipe[pm-postgresql::server]
      - recipe[postgresql::ruby]
      - recipe[test::create_database]
      - recipe[test::drop_database]
    verifier:
      inspec_tests:
        - test/smoke/resources/drop_database_test.rb
    attributes:
      postgresql:
        password:
          postgres: supersecret
